### ISSUE TITLE
Use a client logging library

### ISSUE THREAD

**Issue by aprill1** [googleinterns/cloud-monitoring-notification-delivery-integration-sample-code#12]
https://github.com/googleinterns/cloud-monitoring-notification-delivery-integration-sample-code/blob/dcc6bacf341320dec93329d6f1f0c21c77e9d2ef/main.py#L89-L122

**Comment by stossmt** [comment]
Potentially useful resources: https://flask.palletsprojects.com/en/1.1.x/logging/ and https://cloud.google.com/logging/docs
